### ISSUE TITLE
Anchors and fixed headers

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#125]
The fixed header has the effect of anchors not "working" since they appear underneath the fixed header.

**Comment by NetOperatorWibby** [comment]
Do you have an example? I was pretty sure I fixed this in #111.

**Comment by kauffj** [comment]
Oops, I did think that I had filed this. It was still happening for me in local dev version. Let me check if I need to update (which I thought I did) and/or clear a cache. I'll re-open with more specifics if I think it's still valid.
