### ISSUE TITLE
Can't select text on any pages

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#199]
Can't select text to copy/paste. Thanks to @Invariant-Change for spotting this one.

**Comment by Invariant-Change** [comment]
@tzarebczan https://github.com/lbryio/lbry.tech/pull/200

**Comment by NetOperatorWibby** [comment]
This has been fixed.

**Comment by tzarebczan** [comment]
Still can't select text on https://lbry.tech/resources/daemon-settings

**Comment by gurpreet9001** [comment]
I am working on it.

**Comment by gurpreet9001** [comment]
![capture](https://user-images.githubusercontent.com/26695300/50705108-bf6d1980-107f-11e9-9776-6e7efa4f494b.PNG)
